name: Publish
on:
  release:
    types: [released]
jobs:
  #     ___  __  ________   ___
  #    / _ )/ / / /  _/ /  / _ \
  #   / _  / /_/ // // /__/ // /
  #  /____/\____/___/____/____/
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - uses: actions/upload-artifact@v3
        with:
          name: build_dist
          retention-days: 1
          path: dist

  #     ___  __  _____  __   __________ __
  #    / _ \/ / / / _ )/ /  /  _/ __/ // /
  #   / ___/ /_/ / _  / /___/ /_\ \/ _  /
  #  /_/   \____/____/____/___/___/_//_/
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: build_dist
          path: dist
      - uses: ./.github/actions/publish
        with:
          token: ${{ secrets.PYPI_API_TOKEN }}
